// 都道府県データ
export const PREFECTURES = [
  { code: "13", name: "東京都" },
  { code: "14", name: "神奈川県" },
  { code: "11", name: "埼玉県" },
  { code: "12", name: "千葉県" },
  { code: "27", name: "大阪府" },
  { code: "23", name: "愛知県" },
  { code: "28", name: "兵庫県" },
  { code: "26", name: "京都府" },
  { code: "40", name: "福岡県" },
  { code: "01", name: "北海道" },
  { code: "04", name: "宮城県" },
  { code: "34", name: "広島県" },
  { code: "22", name: "静岡県" },
  { code: "08", name: "茨城県" },
  { code: "09", name: "栃木県" },
  { code: "10", name: "群馬県" },
  { code: "15", name: "新潟県" },
  { code: "20", name: "長野県" },
  { code: "21", name: "岐阜県" },
  { code: "24", name: "三重県" },
  { code: "25", name: "滋賀県" },
  { code: "29", name: "奈良県" },
  { code: "30", name: "和歌山県" },
  { code: "33", name: "岡山県" },
  { code: "35", name: "山口県" },
  { code: "37", name: "香川県" },
  { code: "38", name: "愛媛県" },
  { code: "39", name: "高知県" },
  { code: "41", name: "佐賀県" },
  { code: "42", name: "長崎県" },
  { code: "43", name: "熊本県" },
  { code: "44", name: "大分県" },
  { code: "45", name: "宮崎県" },
  { code: "46", name: "鹿児島県" },
  { code: "47", name: "沖縄県" },
]

// 市区町村データ（都道府県コードでグループ化）
export const MUNICIPALITIES: Record<string, string[]> = {
  "13": [
    "千代田区",
    "中央区",
    "港区",
    "新宿区",
    "文京区",
    "台東区",
    "墨田区",
    "江東区",
    "品川区",
    "目黒区",
    "大田区",
    "世田谷区",
    "渋谷区",
    "中野区",
    "杉並区",
    "豊島区",
    "北区",
    "荒川区",
    "板橋区",
    "練馬区",
    "足立区",
    "葛飾区",
    "江戸川区",
    "八王子市",
    "立川市",
    "武蔵野市",
    "三鷹市",
    "青梅市",
    "府中市",
    "昭島市",
    "調布市",
    "町田市",
    "小金井市",
    "小平市",
    "日野市",
    "東村山市",
    "国分寺市",
    "国立市",
    "福生市",
    "狛江市",
    "東大和市",
    "清瀬市",
    "東久留米市",
    "武蔵村山市",
    "多摩市",
    "稲城市",
    "羽村市",
    "あきる野市",
    "西東京市",
  ],
  "14": [
    "横浜市鶴見区",
    "横浜市神奈川区",
    "横浜市西区",
    "横浜市中区",
    "横浜市南区",
    "横浜市保土ケ谷区",
    "横浜市磯子区",
    "横浜市金沢区",
    "横浜市港北区",
    "横浜市戸塚区",
    "横浜市港南区",
    "横浜市旭区",
    "横浜市緑区",
    "横浜市瀬谷区",
    "横浜市栄区",
    "横浜市泉区",
    "横浜市青葉区",
    "横浜市都筑区",
    "川崎市川崎区",
    "川崎市幸区",
    "川崎市中原区",
    "川崎市高津区",
    "川崎市多摩区",
    "川崎市宮前区",
    "川崎市麻生区",
    "相模原市緑区",
    "相模原市中央区",
    "相模原市南区",
    "横須賀市",
    "平塚市",
    "鎌倉市",
    "藤沢市",
    "小田原市",
    "茅ヶ崎市",
    "逗子市",
    "三浦市",
    "秦野市",
    "厚木市",
    "大和市",
    "伊勢原市",
    "海老名市",
    "座間市",
    "南足柄市",
    "綾瀬市",
  ],
  "11": [
    "さいたま市西区",
    "さいたま市北区",
    "さいたま市大宮区",
    "さいたま市見沼区",
    "さいたま市中央区",
    "さいたま市桜区",
    "さいたま市浦和区",
    "さいたま市南区",
    "さいたま市緑区",
    "さいたま市岩槻区",
    "川越市",
    "熊谷市",
    "川口市",
    "行田市",
    "秩父市",
    "所沢市",
    "飯能市",
    "加須市",
    "本庄市",
    "東松山市",
    "春日部市",
    "狭山市",
    "羽生市",
    "鴻巣市",
    "深谷市",
    "上尾市",
    "草加市",
    "越谷市",
    "蕨市",
    "戸田市",
    "入間市",
    "朝霞市",
    "志木市",
    "和光市",
    "新座市",
    "桶川市",
    "久喜市",
    "北本市",
    "八潮市",
    "富士見市",
    "三郷市",
    "蓮田市",
    "坂戸市",
    "幸手市",
    "鶴ヶ島市",
    "日高市",
    "吉川市",
    "ふじみ野市",
    "白岡市",
  ],
  "12": [
    "千葉市中央区",
    "千葉市花見川区",
    "千葉市稲毛区",
    "千葉市若葉区",
    "千葉市緑区",
    "千葉市美浜区",
    "銚子市",
    "市川市",
    "船橋市",
    "館山市",
    "木更津市",
    "松戸市",
    "野田市",
    "茂原市",
    "成田市",
    "佐倉市",
    "東金市",
    "旭市",
    "習志野市",
    "柏市",
    "勝浦市",
    "市原市",
    "流山市",
    "八千代市",
    "我孫子市",
    "鴨川市",
    "鎌ケ谷市",
    "君津市",
    "富津市",
    "浦安市",
    "四街道市",
    "袖ケ浦市",
    "八街市",
    "印西市",
    "白井市",
    "富里市",
    "南房総市",
    "匝瑳市",
    "香取市",
    "山武市",
    "いすみ市",
    "大網白里市",
  ],
  "27": [
    "大阪市都島区",
    "大阪市福島区",
    "大阪市此花区",
    "大阪市西区",
    "大阪市港区",
    "大阪市大正区",
    "大阪市天王寺区",
    "大阪市浪速区",
    "大阪市西淀川区",
    "大阪市東淀川区",
    "大阪市東成区",
    "大阪市生野区",
    "大阪市旭区",
    "大阪市城東区",
    "大阪市阿倍野区",
    "大阪市住吉区",
    "大阪市東住吉区",
    "大阪市西成区",
    "大阪市淀川区",
    "大阪市鶴見区",
    "大阪市住之江区",
    "大阪市平野区",
    "大阪市北区",
    "大阪市中央区",
    "堺市堺区",
    "堺市中区",
    "堺市東区",
    "堺市西区",
    "堺市南区",
    "堺市北区",
    "堺市美原区",
    "岸和田市",
    "豊中市",
    "池田市",
    "吹田市",
    "泉大津市",
    "高槻市",
    "貝塚市",
    "守口市",
    "枚方市",
    "茨木市",
    "八尾市",
    "泉佐野市",
    "富田林市",
    "寝屋川市",
    "河内長野市",
    "松原市",
    "大東市",
    "和泉市",
    "箕面市",
    "柏原市",
    "羽曳野市",
    "門真市",
    "摂津市",
    "高石市",
    "藤井寺市",
    "東大阪市",
    "泉南市",
    "四條畷市",
    "交野市",
    "大阪狭山市",
    "阪南市",
  ],
  "23": [
    "名古屋市千種区",
    "名古屋市東区",
    "名古屋市北区",
    "名古屋市西区",
    "名古屋市中村区",
    "名古屋市中区",
    "名古屋市昭和区",
    "名古屋市瑞穂区",
    "名古屋市熱田区",
    "名古屋市中川区",
    "名古屋市港区",
    "名古屋市南区",
    "名古屋市守山区",
    "名古屋市緑区",
    "名古屋市名東区",
    "名古屋市天白区",
    "豊橋市",
    "岡崎市",
    "一宮市",
    "瀬戸市",
    "半田市",
    "春日井市",
    "豊川市",
    "津島市",
    "碧南市",
    "刈谷市",
    "豊田市",
    "安城市",
    "西尾市",
    "蒲郡市",
    "犬山市",
    "常滑市",
    "江南市",
    "小牧市",
    "稲沢市",
    "新城市",
    "東海市",
    "大府市",
    "知多市",
    "知立市",
    "尾張旭市",
    "高浜市",
    "岩倉市",
    "豊明市",
    "日進市",
    "田原市",
    "愛西市",
    "清須市",
    "北名古屋市",
    "弥富市",
    "みよし市",
    "あま市",
    "長久手市",
  ],
  "28": [
    "神戸市東灘区",
    "神戸市灘区",
    "神戸市兵庫区",
    "神戸市長田区",
    "神戸市須磨区",
    "神戸市垂水区",
    "神戸市北区",
    "神戸市中央区",
    "神戸市西区",
    "姫路市",
    "尼崎市",
    "明石市",
    "西宮市",
    "洲本市",
    "芦屋市",
    "伊丹市",
    "相生市",
    "豊岡市",
    "加古川市",
    "赤穂市",
    "西脇市",
    "宝塚市",
    "三木市",
    "高砂市",
    "川西市",
    "小野市",
    "三田市",
    "加西市",
    "丹波篠山市",
    "養父市",
    "丹波市",
    "南あわじ市",
    "朝来市",
    "淡路市",
    "宍粟市",
    "加東市",
    "たつの市",
  ],
  "26": [
    "京都市北区",
    "京都市上京区",
    "京都市左京区",
    "京都市中京区",
    "京都市東山区",
    "京都市下京区",
    "京都市南区",
    "京都市右京区",
    "京都市伏見区",
    "京都市山科区",
    "京都市西京区",
    "福知山市",
    "舞鶴市",
    "綾部市",
    "宇治市",
    "宮津市",
    "亀岡市",
    "城陽市",
    "向日市",
    "長岡京市",
    "八幡市",
    "京田辺市",
    "京丹後市",
    "南丹市",
    "木津川市",
  ],
  "40": [
    "北九州市門司区",
    "北九州市若松区",
    "北九州市戸畑区",
    "北九州市小倉北区",
    "北九州市小倉南区",
    "北九州市八幡東区",
    "北九州市八幡西区",
    "福岡市東区",
    "福岡市博多区",
    "福岡市中央区",
    "福岡市南区",
    "福岡市西区",
    "福岡市城南区",
    "福岡市早良区",
    "大牟田市",
    "久留米市",
    "直方市",
    "飯塚市",
    "田川市",
    "柳川市",
    "八女市",
    "筑後市",
    "大川市",
    "行橋市",
    "豊前市",
    "中間市",
    "小郡市",
    "筑紫野市",
    "春日市",
    "大野城市",
    "宗像市",
    "太宰府市",
    "古賀市",
    "福津市",
    "うきは市",
    "宮若市",
    "嘉麻市",
    "朝倉市",
    "みやま市",
    "糸島市",
    "那珂川市",
  ],
  "01": [
    "札幌市中央区",
    "札幌市北区",
    "札幌市東区",
    "札幌市白石区",
    "札幌市豊平区",
    "札幌市南区",
    "札幌市西区",
    "札幌市厚別区",
    "札幌市手稲区",
    "札幌市清田区",
    "函館市",
    "小樽市",
    "旭川市",
    "室蘭市",
    "釧路市",
    "帯広市",
    "北見市",
    "夕張市",
    "岩見沢市",
    "網走市",
    "留萌市",
    "苫小牧市",
    "稚内市",
    "美唄市",
    "芦別市",
    "江別市",
    "赤平市",
    "紋別市",
    "士別市",
    "名寄市",
    "三笠市",
    "根室市",
    "千歳市",
    "滝川市",
    "砂川市",
    "歌志内市",
    "深川市",
    "富良野市",
    "登別市",
    "恵庭市",
    "伊達市",
    "北広島市",
    "石狩市",
    "北斗市",
  ],
}

// サンプル店舗データ（サジェスト用）
export const SAMPLE_STORES: Record<string, { name: string; municipality: string; url?: string }[]> = {
  "13": [
    { name: "カーセレクト東京", municipality: "渋谷区", url: "https://kurumaerabi.com/shop/tokyo001" },
    { name: "オートプラザ新宿", municipality: "新宿区", url: "https://kurumaerabi.com/shop/tokyo002" },
    { name: "プレミアムカーズ品川", municipality: "品川区", url: "https://kurumaerabi.com/shop/tokyo003" },
    { name: "カーランド世田谷", municipality: "世田谷区", url: "https://kurumaerabi.com/shop/tokyo004" },
    { name: "オートセンター池袋", municipality: "豊島区", url: "https://kurumaerabi.com/shop/tokyo005" },
    { name: "ビッグモーター八王子", municipality: "八王子市", url: "https://kurumaerabi.com/shop/tokyo006" },
    { name: "カーチス府中", municipality: "府中市", url: "https://kurumaerabi.com/shop/tokyo007" },
    { name: "ガリバー立川", municipality: "立川市", url: "https://kurumaerabi.com/shop/tokyo008" },
    { name: "ネクステージ町田", municipality: "町田市", url: "https://kurumaerabi.com/shop/tokyo009" },
    { name: "オートバックスカーズ多摩", municipality: "多摩市", url: "https://kurumaerabi.com/shop/tokyo010" },
  ],
  "14": [
    { name: "オートプラザ横浜", municipality: "横浜市中区", url: "https://kurumaerabi.com/shop/kanagawa001" },
    { name: "カーセンター川崎", municipality: "川崎市川崎区", url: "https://kurumaerabi.com/shop/kanagawa002" },
    { name: "湘南カーズ藤沢", municipality: "藤沢市", url: "https://kurumaerabi.com/shop/kanagawa003" },
    { name: "相模原オート", municipality: "相模原市中央区", url: "https://kurumaerabi.com/shop/kanagawa004" },
    { name: "横須賀モータース", municipality: "横須賀市", url: "https://kurumaerabi.com/shop/kanagawa005" },
    { name: "厚木カーセンター", municipality: "厚木市", url: "https://kurumaerabi.com/shop/kanagawa006" },
    { name: "ガリバー横浜港北", municipality: "横浜市港北区", url: "https://kurumaerabi.com/shop/kanagawa007" },
    { name: "ネクステージ横浜", municipality: "横浜市西区", url: "https://kurumaerabi.com/shop/kanagawa008" },
  ],
  "11": [
    { name: "カーセンターさいたま", municipality: "さいたま市大宮区", url: "https://kurumaerabi.com/shop/saitama001" },
    { name: "川越オートプラザ", municipality: "川越市", url: "https://kurumaerabi.com/shop/saitama002" },
    { name: "所沢カーズ", municipality: "所沢市", url: "https://kurumaerabi.com/shop/saitama003" },
    { name: "越谷モータース", municipality: "越谷市", url: "https://kurumaerabi.com/shop/saitama004" },
    { name: "ビッグモーター川口", municipality: "川口市", url: "https://kurumaerabi.com/shop/saitama005" },
    { name: "春日部オート", municipality: "春日部市", url: "https://kurumaerabi.com/shop/saitama006" },
  ],
  "12": [
    { name: "千葉カーセンター", municipality: "千葉市中央区", url: "https://kurumaerabi.com/shop/chiba001" },
    { name: "船橋オートプラザ", municipality: "船橋市", url: "https://kurumaerabi.com/shop/chiba002" },
    { name: "カーランド柏", municipality: "柏市", url: "https://kurumaerabi.com/shop/chiba003" },
    { name: "松戸モータース", municipality: "松戸市", url: "https://kurumaerabi.com/shop/chiba004" },
    { name: "市川カーズ", municipality: "市川市", url: "https://kurumaerabi.com/shop/chiba005" },
    { name: "木更津オート", municipality: "木更津市", url: "https://kurumaerabi.com/shop/chiba006" },
  ],
  "27": [
    { name: "大阪カーセンター", municipality: "大阪市北区", url: "https://kurumaerabi.com/shop/osaka001" },
    { name: "堺オートプラザ", municipality: "堺市堺区", url: "https://kurumaerabi.com/shop/osaka002" },
    { name: "東大阪モータース", municipality: "東大阪市", url: "https://kurumaerabi.com/shop/osaka003" },
    { name: "豊中カーズ", municipality: "豊中市", url: "https://kurumaerabi.com/shop/osaka004" },
    { name: "枚方オート", municipality: "枚方市", url: "https://kurumaerabi.com/shop/osaka005" },
  ],
  "23": [
    { name: "名古屋カーセンター", municipality: "名古屋市中区", url: "https://kurumaerabi.com/shop/aichi001" },
    { name: "豊田オートプラザ", municipality: "豊田市", url: "https://kurumaerabi.com/shop/aichi002" },
    { name: "岡崎モータース", municipality: "岡崎市", url: "https://kurumaerabi.com/shop/aichi003" },
    { name: "一宮カーズ", municipality: "一宮市", url: "https://kurumaerabi.com/shop/aichi004" },
    { name: "春日井オート", municipality: "春日井市", url: "https://kurumaerabi.com/shop/aichi005" },
  ],
  "28": [
    { name: "神戸カーセンター", municipality: "神戸市中央区", url: "https://kurumaerabi.com/shop/hyogo001" },
    { name: "姫路オートプラザ", municipality: "姫路市", url: "https://kurumaerabi.com/shop/hyogo002" },
    { name: "西宮モータース", municipality: "西宮市", url: "https://kurumaerabi.com/shop/hyogo003" },
    { name: "尼崎カーズ", municipality: "尼崎市", url: "https://kurumaerabi.com/shop/hyogo004" },
  ],
  "40": [
    { name: "福岡カーセンター", municipality: "福岡市博多区", url: "https://kurumaerabi.com/shop/fukuoka001" },
    { name: "北九州オートプラザ", municipality: "北九州市小倉北区", url: "https://kurumaerabi.com/shop/fukuoka002" },
    { name: "久留米モータース", municipality: "久留米市", url: "https://kurumaerabi.com/shop/fukuoka003" },
  ],
}

// 店舗名サジェスト関数
export function suggestStores(
  prefectureCode: string,
  municipality: string,
  query: string,
): { name: string; municipality: string; url?: string }[] {
  const stores = SAMPLE_STORES[prefectureCode] || []

  if (!query.trim()) {
    // クエリが空の場合は選択された市区町村の店舗を返す
    if (municipality) {
      return stores.filter((s) => s.municipality === municipality)
    }
    return stores.slice(0, 5)
  }

  // クエリで店舗名をフィルター
  const lowerQuery = query.toLowerCase()
  return stores.filter((s) => s.name.toLowerCase().includes(lowerQuery) || s.municipality.includes(query)).slice(0, 8)
}
